# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'FilterConfig.ui'
#
# Created: Sun Dec 09 18:29:16 2012
#      by: PyQt4 UI code generator 4.9.5
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_filterConfig(object):
    def setupUi(self, filterConfig):
        filterConfig.setObjectName(_fromUtf8("filterConfig"))
        filterConfig.resize(705, 619)
        self.verticalLayout = QtGui.QVBoxLayout(filterConfig)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.filterList = QtGui.QListWidget(filterConfig)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.filterList.sizePolicy().hasHeightForWidth())
        self.filterList.setSizePolicy(sizePolicy)
        self.filterList.setDragEnabled(False)
        self.filterList.setDragDropMode(QtGui.QAbstractItemView.InternalMove)
        self.filterList.setDefaultDropAction(QtCore.Qt.MoveAction)
        self.filterList.setObjectName(_fromUtf8("filterList"))
        self.horizontalLayout.addWidget(self.filterList)
        self.frame = QtGui.QFrame(filterConfig)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.frame)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.label_5 = QtGui.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.verticalLayout_3.addWidget(self.label_5)
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.label = QtGui.QLabel(self.frame)
        self.label.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout_5.addWidget(self.label)
        self.windowCB = QtGui.QComboBox(self.frame)
        self.windowCB.setEnabled(False)
        self.windowCB.setObjectName(_fromUtf8("windowCB"))
        self.verticalLayout_5.addWidget(self.windowCB)
        self.verticalLayout_3.addLayout(self.verticalLayout_5)
        self.groupBox = QtGui.QGroupBox(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.layoutWidget = QtGui.QWidget(self.groupBox)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 10, 271, 121))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.gridLayout = QtGui.QGridLayout(self.layoutWidget)
        self.gridLayout.setMargin(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.lowpassRB = QtGui.QRadioButton(self.layoutWidget)
        self.lowpassRB.setEnabled(False)
        self.lowpassRB.setChecked(True)
        self.lowpassRB.setObjectName(_fromUtf8("lowpassRB"))
        self.gridLayout.addWidget(self.lowpassRB, 0, 0, 1, 1)
        self.highpassRB = QtGui.QRadioButton(self.layoutWidget)
        self.highpassRB.setEnabled(False)
        self.highpassRB.setObjectName(_fromUtf8("highpassRB"))
        self.gridLayout.addWidget(self.highpassRB, 0, 1, 1, 1)
        self.cbandstopRB = QtGui.QRadioButton(self.layoutWidget)
        self.cbandstopRB.setEnabled(False)
        self.cbandstopRB.setObjectName(_fromUtf8("cbandstopRB"))
        self.gridLayout.addWidget(self.cbandstopRB, 1, 0, 1, 1)
        self.vbandstopRB = QtGui.QRadioButton(self.layoutWidget)
        self.vbandstopRB.setEnabled(False)
        self.vbandstopRB.setObjectName(_fromUtf8("vbandstopRB"))
        self.gridLayout.addWidget(self.vbandstopRB, 1, 1, 1, 1)
        self.hbandstopRB = QtGui.QRadioButton(self.layoutWidget)
        self.hbandstopRB.setEnabled(False)
        self.hbandstopRB.setObjectName(_fromUtf8("hbandstopRB"))
        self.gridLayout.addWidget(self.hbandstopRB, 2, 0, 1, 1)
        self.notchRB = QtGui.QRadioButton(self.layoutWidget)
        self.notchRB.setEnabled(False)
        self.notchRB.setObjectName(_fromUtf8("notchRB"))
        self.gridLayout.addWidget(self.notchRB, 2, 1, 1, 1)
        self.verticalLayout_3.addWidget(self.groupBox)
        self.frame_2 = QtGui.QFrame(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(3)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setObjectName(_fromUtf8("frame_2"))
        self.layoutWidget1 = QtGui.QWidget(self.frame_2)
        self.layoutWidget1.setGeometry(QtCore.QRect(12, 23, 301, 126))
        self.layoutWidget1.setObjectName(_fromUtf8("layoutWidget1"))
        self.gridLayout_2 = QtGui.QGridLayout(self.layoutWidget1)
        self.gridLayout_2.setMargin(0)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.label_3 = QtGui.QLabel(self.layoutWidget1)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_2.addWidget(self.label_3, 1, 1, 1, 1)
        self.widthSB = QtGui.QSpinBox(self.layoutWidget1)
        self.widthSB.setEnabled(False)
        self.widthSB.setMinimum(1)
        self.widthSB.setMaximum(99999)
        self.widthSB.setSingleStep(2)
        self.widthSB.setProperty("value", 3)
        self.widthSB.setObjectName(_fromUtf8("widthSB"))
        self.gridLayout_2.addWidget(self.widthSB, 1, 0, 1, 1)
        self.diameterSB = QtGui.QSpinBox(self.layoutWidget1)
        self.diameterSB.setEnabled(False)
        self.diameterSB.setMinimum(1)
        self.diameterSB.setMaximum(99999)
        self.diameterSB.setProperty("value", 128)
        self.diameterSB.setObjectName(_fromUtf8("diameterSB"))
        self.gridLayout_2.addWidget(self.diameterSB, 0, 0, 1, 1)
        self.label_2 = QtGui.QLabel(self.layoutWidget1)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_2.addWidget(self.label_2, 0, 1, 1, 1)
        self.label_6 = QtGui.QLabel(self.layoutWidget1)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_2.addWidget(self.label_6, 3, 1, 1, 1)
        self.label_4 = QtGui.QLabel(self.layoutWidget1)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_2.addWidget(self.label_4, 2, 1, 1, 1)
        self.shapeSB = QtGui.QDoubleSpinBox(self.layoutWidget1)
        self.shapeSB.setEnabled(False)
        self.shapeSB.setMaximum(9999999.0)
        self.shapeSB.setSingleStep(0.01)
        self.shapeSB.setProperty("value", 1.0)
        self.shapeSB.setObjectName(_fromUtf8("shapeSB"))
        self.gridLayout_2.addWidget(self.shapeSB, 2, 0, 1, 1)
        self.label_7 = QtGui.QLabel(self.layoutWidget1)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_2.addWidget(self.label_7, 4, 1, 1, 1)
        self.hcenterSB = QtGui.QSpinBox(self.layoutWidget1)
        self.hcenterSB.setEnabled(False)
        self.hcenterSB.setMinimum(1)
        self.hcenterSB.setMaximum(99999)
        self.hcenterSB.setObjectName(_fromUtf8("hcenterSB"))
        self.gridLayout_2.addWidget(self.hcenterSB, 3, 0, 1, 1)
        self.vcenterSB = QtGui.QSpinBox(self.layoutWidget1)
        self.vcenterSB.setEnabled(False)
        self.vcenterSB.setMinimum(1)
        self.vcenterSB.setMaximum(99999)
        self.vcenterSB.setObjectName(_fromUtf8("vcenterSB"))
        self.gridLayout_2.addWidget(self.vcenterSB, 4, 0, 1, 1)
        self.verticalLayout_3.addWidget(self.frame_2)
        self.groupBox_3 = QtGui.QGroupBox(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.groupBox_3.sizePolicy().hasHeightForWidth())
        self.groupBox_3.setSizePolicy(sizePolicy)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.layoutWidget2 = QtGui.QWidget(self.groupBox_3)
        self.layoutWidget2.setGeometry(QtCore.QRect(10, 20, 251, 20))
        self.layoutWidget2.setObjectName(_fromUtf8("layoutWidget2"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.layoutWidget2)
        self.horizontalLayout_4.setMargin(0)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.outerRB = QtGui.QRadioButton(self.layoutWidget2)
        self.outerRB.setEnabled(False)
        self.outerRB.setObjectName(_fromUtf8("outerRB"))
        self.horizontalLayout_4.addWidget(self.outerRB)
        self.rotationalRB = QtGui.QRadioButton(self.layoutWidget2)
        self.rotationalRB.setEnabled(False)
        self.rotationalRB.setChecked(True)
        self.rotationalRB.setObjectName(_fromUtf8("rotationalRB"))
        self.horizontalLayout_4.addWidget(self.rotationalRB)
        self.verticalLayout_3.addWidget(self.groupBox_3)
        self.groupBox_2 = QtGui.QGroupBox(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.layoutWidget3 = QtGui.QWidget(self.groupBox_2)
        self.layoutWidget3.setGeometry(QtCore.QRect(10, 20, 251, 20))
        self.layoutWidget3.setObjectName(_fromUtf8("layoutWidget3"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.layoutWidget3)
        self.horizontalLayout_3.setMargin(0)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.pixelRB = QtGui.QRadioButton(self.layoutWidget3)
        self.pixelRB.setEnabled(False)
        self.pixelRB.setObjectName(_fromUtf8("pixelRB"))
        self.horizontalLayout_3.addWidget(self.pixelRB)
        self.percentRB = QtGui.QRadioButton(self.layoutWidget3)
        self.percentRB.setEnabled(False)
        self.percentRB.setChecked(True)
        self.percentRB.setObjectName(_fromUtf8("percentRB"))
        self.horizontalLayout_3.addWidget(self.percentRB)
        self.verticalLayout_3.addWidget(self.groupBox_2)
        self.verticalLayout_6.addLayout(self.verticalLayout_3)
        self.horizontalLayout.addWidget(self.frame)
        self.filterDisplay = mplCanvas(filterConfig)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(3)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.filterDisplay.sizePolicy().hasHeightForWidth())
        self.filterDisplay.setSizePolicy(sizePolicy)
        self.filterDisplay.setObjectName(_fromUtf8("filterDisplay"))
        self.horizontalLayout.addWidget(self.filterDisplay)
        self.horizontalLayout.setStretch(1, 6)
        self.horizontalLayout.setStretch(2, 5)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.newButton = QtGui.QPushButton(filterConfig)
        self.newButton.setObjectName(_fromUtf8("newButton"))
        self.horizontalLayout_2.addWidget(self.newButton)
        self.removeButton = QtGui.QPushButton(filterConfig)
        self.removeButton.setObjectName(_fromUtf8("removeButton"))
        self.horizontalLayout_2.addWidget(self.removeButton)
        self.buttonBox = QtGui.QDialogButtonBox(filterConfig)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.horizontalLayout_2.addWidget(self.buttonBox)
        self.verticalLayout.addLayout(self.horizontalLayout_2)

        self.retranslateUi(filterConfig)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), filterConfig.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), filterConfig.reject)
        QtCore.QMetaObject.connectSlotsByName(filterConfig)

    def retranslateUi(self, filterConfig):
        filterConfig.setWindowTitle(QtGui.QApplication.translate("filterConfig", "Configure Filters", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("filterConfig", "Configure Filter", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("filterConfig", "Filter Window", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("filterConfig", "Filter Type", None, QtGui.QApplication.UnicodeUTF8))
        self.lowpassRB.setText(QtGui.QApplication.translate("filterConfig", "Low Pass", None, QtGui.QApplication.UnicodeUTF8))
        self.highpassRB.setText(QtGui.QApplication.translate("filterConfig", "High Pass", None, QtGui.QApplication.UnicodeUTF8))
        self.cbandstopRB.setText(QtGui.QApplication.translate("filterConfig", "Circular Band Stop", None, QtGui.QApplication.UnicodeUTF8))
        self.vbandstopRB.setText(QtGui.QApplication.translate("filterConfig", "Vertical Band Stop", None, QtGui.QApplication.UnicodeUTF8))
        self.hbandstopRB.setText(QtGui.QApplication.translate("filterConfig", "Horizontal Band Stop", None, QtGui.QApplication.UnicodeUTF8))
        self.notchRB.setText(QtGui.QApplication.translate("filterConfig", "Notch", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("filterConfig", "Width", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("filterConfig", "Diameter", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("filterConfig", "Horizontal Center", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("filterConfig", "Shape", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("filterConfig", "Vertical Center", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_3.setTitle(QtGui.QApplication.translate("filterConfig", "Construction Method", None, QtGui.QApplication.UnicodeUTF8))
        self.outerRB.setText(QtGui.QApplication.translate("filterConfig", "Outer Product", None, QtGui.QApplication.UnicodeUTF8))
        self.rotationalRB.setText(QtGui.QApplication.translate("filterConfig", "Rotational", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("filterConfig", "Constant Magnitude Contour", None, QtGui.QApplication.UnicodeUTF8))
        self.pixelRB.setText(QtGui.QApplication.translate("filterConfig", "Pixel", None, QtGui.QApplication.UnicodeUTF8))
        self.percentRB.setText(QtGui.QApplication.translate("filterConfig", "Percentage", None, QtGui.QApplication.UnicodeUTF8))
        self.newButton.setText(QtGui.QApplication.translate("filterConfig", "New Filter", None, QtGui.QApplication.UnicodeUTF8))
        self.removeButton.setText(QtGui.QApplication.translate("filterConfig", "Remove Filter", None, QtGui.QApplication.UnicodeUTF8))

from mplwidget import mplCanvas
