# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created: Sat Feb  9 21:01:10 2013
#      by: PyQt4 UI code generator 4.9.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(862, 822)
        MainWindow.setDockOptions(QtGui.QMainWindow.AllowNestedDocks|QtGui.QMainWindow.AllowTabbedDocks|QtGui.QMainWindow.AnimatedDocks)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 862, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuOpen = QtGui.QMenu(self.menuFile)
        self.menuOpen.setObjectName(_fromUtf8("menuOpen"))
        self.menuFilter = QtGui.QMenu(self.menubar)
        self.menuFilter.setObjectName(_fromUtf8("menuFilter"))
        self.menuSettings = QtGui.QMenu(self.menubar)
        self.menuSettings.setObjectName(_fromUtf8("menuSettings"))
        self.menuContrast = QtGui.QMenu(self.menubar)
        self.menuContrast.setObjectName(_fromUtf8("menuContrast"))
        self.menuWindows = QtGui.QMenu(self.menubar)
        self.menuWindows.setObjectName(_fromUtf8("menuWindows"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.kspaceDock = QtGui.QDockWidget(MainWindow)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.kspaceDock.sizePolicy().hasHeightForWidth())
        self.kspaceDock.setSizePolicy(sizePolicy)
        self.kspaceDock.setAllowedAreas(QtCore.Qt.AllDockWidgetAreas)
        self.kspaceDock.setObjectName(_fromUtf8("kspaceDock"))
        self.kspaceDockContents = QtGui.QWidget()
        self.kspaceDockContents.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.kspaceDockContents.setObjectName(_fromUtf8("kspaceDockContents"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout(self.kspaceDockContents)
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.kspace = mplCanvas(self.kspaceDockContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.kspace.sizePolicy().hasHeightForWidth())
        self.kspace.setSizePolicy(sizePolicy)
        self.kspace.setCursor(QtGui.QCursor(QtCore.Qt.CrossCursor))
        self.kspace.setObjectName(_fromUtf8("kspace"))
        self.horizontalLayout_6.addWidget(self.kspace)
        self.kspaceDock.setWidget(self.kspaceDockContents)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(2), self.kspaceDock)
        self.kspacePhaseDock = QtGui.QDockWidget(MainWindow)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.kspacePhaseDock.sizePolicy().hasHeightForWidth())
        self.kspacePhaseDock.setSizePolicy(sizePolicy)
        self.kspacePhaseDock.setAllowedAreas(QtCore.Qt.AllDockWidgetAreas)
        self.kspacePhaseDock.setObjectName(_fromUtf8("kspacePhaseDock"))
        self.kspacePhaseDockContents = QtGui.QWidget()
        self.kspacePhaseDockContents.setObjectName(_fromUtf8("kspacePhaseDockContents"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.kspacePhaseDockContents)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.kspacePhase = mplCanvas(self.kspacePhaseDockContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.kspacePhase.sizePolicy().hasHeightForWidth())
        self.kspacePhase.setSizePolicy(sizePolicy)
        self.kspacePhase.setCursor(QtGui.QCursor(QtCore.Qt.CrossCursor))
        self.kspacePhase.setObjectName(_fromUtf8("kspacePhase"))
        self.horizontalLayout_5.addWidget(self.kspacePhase)
        self.kspacePhaseDock.setWidget(self.kspacePhaseDockContents)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(2), self.kspacePhaseDock)
        self.magnitudeDock = QtGui.QDockWidget(MainWindow)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.magnitudeDock.sizePolicy().hasHeightForWidth())
        self.magnitudeDock.setSizePolicy(sizePolicy)
        self.magnitudeDock.setObjectName(_fromUtf8("magnitudeDock"))
        self.magnitudeDockContents = QtGui.QWidget()
        self.magnitudeDockContents.setObjectName(_fromUtf8("magnitudeDockContents"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.magnitudeDockContents)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.magnitudeImage = mplCanvas(self.magnitudeDockContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.magnitudeImage.sizePolicy().hasHeightForWidth())
        self.magnitudeImage.setSizePolicy(sizePolicy)
        self.magnitudeImage.setCursor(QtGui.QCursor(QtCore.Qt.CrossCursor))
        self.magnitudeImage.setObjectName(_fromUtf8("magnitudeImage"))
        self.horizontalLayout_4.addWidget(self.magnitudeImage)
        self.magnitudeDock.setWidget(self.magnitudeDockContents)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.magnitudeDock)
        self.phaseDock = QtGui.QDockWidget(MainWindow)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.phaseDock.sizePolicy().hasHeightForWidth())
        self.phaseDock.setSizePolicy(sizePolicy)
        self.phaseDock.setAllowedAreas(QtCore.Qt.AllDockWidgetAreas)
        self.phaseDock.setObjectName(_fromUtf8("phaseDock"))
        self.phaseDockContents = QtGui.QWidget()
        self.phaseDockContents.setObjectName(_fromUtf8("phaseDockContents"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.phaseDockContents)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.phaseImage = mplCanvas(self.phaseDockContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.phaseImage.sizePolicy().hasHeightForWidth())
        self.phaseImage.setSizePolicy(sizePolicy)
        self.phaseImage.setCursor(QtGui.QCursor(QtCore.Qt.CrossCursor))
        self.phaseImage.setObjectName(_fromUtf8("phaseImage"))
        self.horizontalLayout_3.addWidget(self.phaseImage)
        self.phaseDock.setWidget(self.phaseDockContents)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.phaseDock)
        self.dataExplorerDock = QtGui.QDockWidget(MainWindow)
        self.dataExplorerDock.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dataExplorerDock.sizePolicy().hasHeightForWidth())
        self.dataExplorerDock.setSizePolicy(sizePolicy)
        self.dataExplorerDock.setMinimumSize(QtCore.QSize(270, 100))
        self.dataExplorerDock.setFloating(False)
        self.dataExplorerDock.setFeatures(QtGui.QDockWidget.AllDockWidgetFeatures)
        self.dataExplorerDock.setAllowedAreas(QtCore.Qt.AllDockWidgetAreas)
        self.dataExplorerDock.setObjectName(_fromUtf8("dataExplorerDock"))
        self.ExplorerDockContents = QtGui.QWidget()
        self.ExplorerDockContents.setObjectName(_fromUtf8("ExplorerDockContents"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.ExplorerDockContents)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.label_2 = QtGui.QLabel(self.ExplorerDockContents)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.verticalLayout_2.addWidget(self.label_2)
        self.label_4 = QtGui.QLabel(self.ExplorerDockContents)
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.verticalLayout_2.addWidget(self.label_4)
        self.label_3 = QtGui.QLabel(self.ExplorerDockContents)
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.verticalLayout_2.addWidget(self.label_3)
        self.label = QtGui.QLabel(self.ExplorerDockContents)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout_2.addWidget(self.label)
        self.clearIButton = QtGui.QPushButton(self.ExplorerDockContents)
        self.clearIButton.setObjectName(_fromUtf8("clearIButton"))
        self.verticalLayout_2.addWidget(self.clearIButton)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.iMag = QtGui.QLabel(self.ExplorerDockContents)
        self.iMag.setAutoFillBackground(False)
        self.iMag.setText(_fromUtf8(""))
        self.iMag.setObjectName(_fromUtf8("iMag"))
        self.verticalLayout.addWidget(self.iMag)
        self.iPhase = QtGui.QLabel(self.ExplorerDockContents)
        self.iPhase.setText(_fromUtf8(""))
        self.iPhase.setObjectName(_fromUtf8("iPhase"))
        self.verticalLayout.addWidget(self.iPhase)
        self.kMag = QtGui.QLabel(self.ExplorerDockContents)
        self.kMag.setText(_fromUtf8(""))
        self.kMag.setObjectName(_fromUtf8("kMag"))
        self.verticalLayout.addWidget(self.kMag)
        self.kPhase = QtGui.QLabel(self.ExplorerDockContents)
        self.kPhase.setText(_fromUtf8(""))
        self.kPhase.setObjectName(_fromUtf8("kPhase"))
        self.verticalLayout.addWidget(self.kPhase)
        self.clearKButton = QtGui.QPushButton(self.ExplorerDockContents)
        self.clearKButton.setObjectName(_fromUtf8("clearKButton"))
        self.verticalLayout.addWidget(self.clearKButton)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.horizontalLayout.setStretch(0, 1)
        self.horizontalLayout.setStretch(1, 1)
        self.horizontalLayout_2.addLayout(self.horizontalLayout)
        self.dataExplorerDock.setWidget(self.ExplorerDockContents)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(8), self.dataExplorerDock)
        self.actionColor_Maps = QtGui.QAction(MainWindow)
        self.actionColor_Maps.setObjectName(_fromUtf8("actionColor_Maps"))
        self.actionKspace = QtGui.QAction(MainWindow)
        self.actionKspace.setObjectName(_fromUtf8("actionKspace"))
        self.actionKspace_Phase = QtGui.QAction(MainWindow)
        self.actionKspace_Phase.setObjectName(_fromUtf8("actionKspace_Phase"))
        self.actionMagnitude = QtGui.QAction(MainWindow)
        self.actionMagnitude.setObjectName(_fromUtf8("actionMagnitude"))
        self.actionPhase_Map = QtGui.QAction(MainWindow)
        self.actionPhase_Map.setObjectName(_fromUtf8("actionPhase_Map"))
        self.actionConfigureFilters = QtGui.QAction(MainWindow)
        self.actionConfigureFilters.setObjectName(_fromUtf8("actionConfigureFilters"))
        self.actionExit = QtGui.QAction(MainWindow)
        self.actionExit.setObjectName(_fromUtf8("actionExit"))
        self.actionFID = QtGui.QAction(MainWindow)
        self.actionFID.setObjectName(_fromUtf8("actionFID"))
        self.actionP_File = QtGui.QAction(MainWindow)
        self.actionP_File.setObjectName(_fromUtf8("actionP_File"))
        self.actionData_Explorer = QtGui.QAction(MainWindow)
        self.actionData_Explorer.setObjectName(_fromUtf8("actionData_Explorer"))
        self.actionMagnitude_Image = QtGui.QAction(MainWindow)
        self.actionMagnitude_Image.setObjectName(_fromUtf8("actionMagnitude_Image"))
        self.actionPhase_Image = QtGui.QAction(MainWindow)
        self.actionPhase_Image.setObjectName(_fromUtf8("actionPhase_Image"))
        self.actionK_space = QtGui.QAction(MainWindow)
        self.actionK_space.setObjectName(_fromUtf8("actionK_space"))
        self.actionK_space_Phase = QtGui.QAction(MainWindow)
        self.actionK_space_Phase.setObjectName(_fromUtf8("actionK_space_Phase"))
        self.menuOpen.addAction(self.actionFID)
        self.menuOpen.addAction(self.actionP_File)
        self.menuFile.addAction(self.menuOpen.menuAction())
        self.menuFile.addAction(self.actionExit)
        self.menuFilter.addAction(self.actionConfigureFilters)
        self.menuSettings.addAction(self.actionColor_Maps)
        self.menuContrast.addAction(self.actionKspace)
        self.menuContrast.addAction(self.actionKspace_Phase)
        self.menuContrast.addAction(self.actionMagnitude)
        self.menuContrast.addAction(self.actionPhase_Map)
        self.menuWindows.addAction(self.actionData_Explorer)
        self.menuWindows.addAction(self.actionMagnitude_Image)
        self.menuWindows.addAction(self.actionPhase_Image)
        self.menuWindows.addAction(self.actionK_space)
        self.menuWindows.addAction(self.actionK_space_Phase)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuFilter.menuAction())
        self.menubar.addAction(self.menuContrast.menuAction())
        self.menubar.addAction(self.menuSettings.menuAction())
        self.menubar.addAction(self.menuWindows.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MR Magic", None))
        self.menuFile.setTitle(_translate("MainWindow", "File", None))
        self.menuOpen.setTitle(_translate("MainWindow", "Open", None))
        self.menuFilter.setTitle(_translate("MainWindow", "Filter", None))
        self.menuSettings.setTitle(_translate("MainWindow", "Settings", None))
        self.menuContrast.setTitle(_translate("MainWindow", "Contrast", None))
        self.menuWindows.setTitle(_translate("MainWindow", "Windows", None))
        self.kspaceDock.setWindowTitle(_translate("MainWindow", "K-Space", None))
        self.kspacePhaseDock.setWindowTitle(_translate("MainWindow", "K-Space Phase", None))
        self.magnitudeDock.setWindowTitle(_translate("MainWindow", "Magnitude", None))
        self.phaseDock.setWindowTitle(_translate("MainWindow", "Phase", None))
        self.dataExplorerDock.setWindowTitle(_translate("MainWindow", "Data Explorer", None))
        self.label_2.setText(_translate("MainWindow", "Image Magnitude:", None))
        self.label_4.setText(_translate("MainWindow", "Image Phase:", None))
        self.label_3.setText(_translate("MainWindow", "Kspace Magnitude:", None))
        self.label.setText(_translate("MainWindow", "Kspace Phase:", None))
        self.clearIButton.setText(_translate("MainWindow", "Clear Image Markers", None))
        self.clearKButton.setText(_translate("MainWindow", "Clear Kspace Markers", None))
        self.actionColor_Maps.setText(_translate("MainWindow", "Color Maps", None))
        self.actionKspace.setText(_translate("MainWindow", "Kspace", None))
        self.actionKspace_Phase.setText(_translate("MainWindow", "Kspace Phase", None))
        self.actionMagnitude.setText(_translate("MainWindow", "Magnitude", None))
        self.actionPhase_Map.setText(_translate("MainWindow", "Phase Map", None))
        self.actionConfigureFilters.setText(_translate("MainWindow", "Configure Filters", None))
        self.actionExit.setText(_translate("MainWindow", "Exit", None))
        self.actionFID.setText(_translate("MainWindow", "FID", None))
        self.actionP_File.setText(_translate("MainWindow", "P-File", None))
        self.actionData_Explorer.setText(_translate("MainWindow", "Data Explorer", None))
        self.actionMagnitude_Image.setText(_translate("MainWindow", "Magnitude Image", None))
        self.actionPhase_Image.setText(_translate("MainWindow", "Phase Image", None))
        self.actionK_space.setText(_translate("MainWindow", "K-space", None))
        self.actionK_space_Phase.setText(_translate("MainWindow", "K-space Phase", None))

from mplwidget import mplCanvas
